env:
  browser: true
  es2021: true
  node: true
extends: airbnb-base
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }],
  no-console: 0,
  import/extensions: 0,
}
