import { getRandomColor } from '../src/utils.js';

let counter = 0;
const colors = [
  'hsl(197 30% 43%)',
  'hsl(173 58% 39%)',
  'hsl(43 74% 66%)',
  'hsl(27 87% 67%)',
  'hsl(12 76% 61%)',
  'hsl(350 60% 52%)',
  'hsl(91 43% 54%)',
  'hsl(140 36% 74%)',
];

export default [
  {
    name: 'Dan',
    secondName: 'Bilzerian',
    phone: '79184829267',
    prize: '',
    displayName: `Участник #${counter += 1}`,
    color: getRandomColor(colors),
  },
  {
    name: 'Phil',
    secondName: 'Ivey',
    phone: '79188812057',
    prize: '',
    displayName: `Участник #${counter += 1}`,
    color: getRandomColor(colors),
  },
  {
    name: 'Iskhan',
    secondName: 'Farha',
    phone: '79187037652',
    prize: '',
    displayName: `Участник #${counter += 1}`,
    color: getRandomColor(colors),
  },
  {
    name: 'Chris',
    secondName: 'Ferguson',
    phone: '79180348860',
    prize: '',
    displayName: `Участник #${counter += 1}`,
    color: getRandomColor(colors),
  },
  {
    name: 'Doyle',
    secondName: 'Brunson',
    phone: '79183022867',
    prize: '',
    displayName: `Участник #${counter += 1}`,
    color: getRandomColor(colors),
  },
  {
    name: 'Archie',
    secondName: 'Karas',
    phone: '79185995478',
    prize: '',
    displayName: `Участник #${counter += 1}`,
    color: getRandomColor(colors),
  },
  {
    name: 'John',
    secondName: 'Heywood',
    phone: '79187283815',
    prize: '',
    displayName: `Участник #${counter += 1}`,
    color: getRandomColor(colors),
  },
  {
    name: 'Cynthia',
    secondName: 'Jay',
    phone: '79185083787',
    prize: '',
    displayName: `Участник #${counter += 1}`,
    color: getRandomColor(colors),
  },
  {
    name: 'Joe',
    secondName: 'Barefoot',
    phone: '79188047714',
    prize: '',
    displayName: `Участник #${counter += 1}`,
    color: getRandomColor(colors),
  },
  {
    name: 'William',
    secondName: 'Bergstrom',
    phone: '79180484276',
    prize: '',
    displayName: `Участник #${counter += 1}`,
    color: getRandomColor(colors),
  },
];
