let counter = 0;

export default [
  {
    name: 'Dan',
    secondName: 'Bilzerian',
    city: 'Krasnodar',
    phone: '79184829267',
    prize: '',
    displayName: `Участник #${counter += 1}`,
  },
  {
    name: 'Phil',
    secondName: 'Ivey',
    city: 'Sochi',
    phone: '79188812057',
    prize: '',
    displayName: `Участник #${counter += 1}`,
  },
  {
    name: 'Iskhan',
    secondName: 'Farha',
    city: 'Novorossiysk',
    phone: '79187037652',
    prize: '',
    displayName: `Участник #${counter += 1}`,
  },
  {
    name: 'Chris',
    secondName: 'Ferguson',
    city: 'Armavir',
    phone: '79180348860',
    prize: '',
    displayName: `Участник #${counter += 1}`,
  },
  {
    name: 'Doyle',
    secondName: 'Brunson',
    city: 'Yeysk',
    phone: '79183022867',
    prize: '',
    displayName: `Участник #${counter += 1}`,
  },
  {
    name: 'Archie',
    secondName: 'Karas',
    city: 'Kropotkin',
    phone: '79185995478',
    prize: '',
    displayName: `Участник #${counter += 1}`,
  },
  {
    name: 'John',
    secondName: 'Heywood',
    city: 'Slavyansk-na-Kubani',
    phone: '79187283815',
    prize: '',
    displayName: `Участник #${counter += 1}`,
  },
  {
    name: 'Cynthia',
    secondName: 'Jay',
    city: 'Tuapse',
    phone: '79185083787',
    prize: '',
    displayName: `Участник #${counter += 1}`,
  },
  {
    name: 'Joe',
    secondName: 'Barefoot',
    city: 'Tikhoretsk',
    phone: '79188047714',
    prize: '',
    displayName: `Участник #${counter += 1}`,
  },
  {
    name: 'William',
    secondName: 'Bergstrom',
    city: 'Labinsk',
    phone: '79180484276',
    prize: '',
    displayName: `Участник #${counter += 1}`,
  },
];
